### ISSUE TITLE
Ephemeral nodes

### ISSUE THREAD

**Issue by lloydwatkin** [buddycloud/buddycloud-server-java#270]
This lists the tasks required for ephemeral nodes:

- [x] Prevent deletion of ephemeral nodes #269
- [x] Allow nodes to be 'hidden' from disco#items #264
- [x] Configure nodes as ephemeral #263 
- [x] Don't include ephemeral nodes in subscriptions unless requested
- [x] All users in ephemeral nodes are moderators (or owner) regardless of their affiliation - set on subscribe #271 
- [x] Prevent owners/moderators changing affiliation to anything but owner/moderator for ephemeral nodes #272 
- [x] Ephemeral nodes are deleted when the last user leaves #273 

@imaginator, @abmargb anything I've missed?

## Issues

- [x] Moderators can not affect affiliation of other moderators (or owners) #275

**Comment by imaginator** [comment]
Thanks for doing this!
